activeCategoryNames = {
    "bay": "networks",
    "job-hunt-buddies": "networks",
    "resumes": "networks",
    "japanese-language": "international",
    "book-club": "networks",
    "system-design": "curriculum helpers",
    "python": "curriculum helpers",
    "accessiblity": "curriculum helpers",
    "git": "curriculum helpers",
    "seattle": "networks",
    "security": "curriculum helpers",
    "french-language": "networks",
    "refer-a-recruiter": "networks",
    "css-and-styling": "curriculum helpers",
    "java": "curriculum helpers",
    "databases": "curriculum helpers",
    "ruby-on-rails": "curriculum helpers",
    "shell": "curriculum helpers",
    "code-talk-links": "networks",
    "react-native": "curriculum helpers",
    "vue": "curriculum helpers",
    "cloud-serverless": "curriculum helpers",
    "creator-support": "networks",
    "code-review": "networks",
    "wiki": "curriculum helpers",
    "test-channel": "Text Channels"
}
